### ISSUE TITLE
API overhaul

### ISSUE THREAD

**Issue by ybnd** [ybnd/shapeflow#14]
### Todo:
* [x] Deprecate `RootInstance`and its nested instance tracking mechanism
	* All calls to nested instances in `shapeflow.video` should go through `VideoAnalyzer` wrappers
* [x] Deprecate messy `Endpoint`/`EndpointRegistry` stuff
* [x] Define a `Dispatcher` class
	* Keep track of nested `Endpoint` instances and map their exposed methods to an address space
	* Can contain other `Dispatcher` instances and include their methods in the address space as well
		* On any changes, a `Dispatcher` pushes its address space to its parent `Dispatcher`
		* In the end, the root `Dispatcher` instance `shapeflow.api.api` will map all addresses in the API to their respective methods.
		* For example, the URL `/api/<id>/call/analyze` becomes `/api/va/<id>/analyze`, where `api`, `va` and  `__id__` are `Dispatcher` instances
                * The `VideoAnalyzerManagerDispatcher` `__id__` is a "special" `Dispatcher` which keeps track of `BaseVideoAnalyzer` instances (without knowing their implementation details)
	         * `Endpoint` keep track of class-level methods (unbound), so in this way the API can publish endpoints bound to specific instances
* [x] Shorter IDs for analyzers
* [x] Clean up `Dispatcher` implementation
* [x] Implement a `VideoAnalyzerManager` class to handle `VideoAnalyzer` instantiation and registration with `VideoAnalyzerManagerDispatcher`
	- This class should also handle queue operations and closing, and any new functionality on an "all analyzers" level
* [x] Add a similar mechanism to instantiate `History` and make sure the methods exposed under `/api/db` are bound to it
* [x] Split `shapeflow.server.Server` into a general server and an application server
	- The general server serves files and defers `/api/` requests to the API (and implement #13)
	- The general server starts first so the frontend can be served sooner
	- The bulk of the backend library should be loaded lazily, since it's the slowest part
	- All `/api/` requests should be handled by `shapeflow.api.api`
* [x] Update frontend
* [x] Update backend tests
* [x] Update frontend tests

### New (?) issues:
* [x] Requests to non-existant `/api/` endpoints return a `{status: 200, data: 'true'}` response for some reason. 
> Catch exceptions & abort with 404
* [x] Cache doesn't work
> due to removing caching context propagation. Removed caching context altogether, CachingInstance should either have an open cache if caching is enabled in the settings, or it shouldn't have a cache at all. Some test will have to be updated though.
* [x] **?** Multiple copies of analyzers seem to open on load_state
> Solved itself in some way?
* [x] **?** Collisions when adding models to SQLAlchemy session
> Possibly solved with fail/wait/retry/raise strategy
