### ISSUE TITLE
Application quits immediately

### ISSUE THREAD

**Issue by ybnd** [ybnd/shapeflow#60]
Various issues getting the app to deploy on Windows machines for the first time.
The "immediate quit" issue appears to have been a 0.4.1 issue, not planning to investigate that further.

#### TODO:

* [x] "tech support call"
* [x] ~~Confirm whether MS Visual Studio C++ build tools are actually necessary
      Presumably this would be required by `opencv`, wasn't `opencv-python` supposed to ship binaries -- why is this still necassary?~~
      Just Python 3.10 seems sufficient on Windows
* [x] Confirm whether Python 3.10 is necessary
  * ~~What's going wrong with 3.8 exactly? (didn't work even in combo with the C++ build tools)~~ don't care
  * What about 3.9? ~~3.7~~ don't care
* [x] Once both are cleared up: document prerequisites
* [ ] Double check Windows installs w/ Python 3.9 and 3.10 _but without MS Visual Studio C++ tools_
* [ ] Maybe: clearer output in deploy script
